"""BDP Package
   -----------

   This package contains specific implementations of ADMIT Basic Data Products, 
   derived from the BDP base class.
"""
# This file is automatically generated, do not edit.

# Standard, streamlined BDP names.
from BDP                        import BDP                        as BDP
from CubeSpectrum_BDP           import CubeSpectrum_BDP           as CubeSpectrum_BDP
from CubeStats_BDP              import CubeStats_BDP              as CubeStats_BDP
from DescriptionVector_BDP      import DescriptionVector_BDP      as DescriptionVector_BDP
from Dual_inherit_BDP           import Dual_inherit_BDP           as Dual_inherit_BDP
from FeatureList_BDP            import FeatureList_BDP            as FeatureList_BDP
from File_BDP                   import File_BDP                   as File_BDP
from Image_BDP                  import Image_BDP                  as Image_BDP
from Image_inherit_BDP          import Image_inherit_BDP          as Image_inherit_BDP
from LineCube_BDP               import LineCube_BDP               as LineCube_BDP
from LineImage_BDP              import LineImage_BDP              as LineImage_BDP
from LineList_BDP               import LineList_BDP               as LineList_BDP
from LineSegment_BDP            import LineSegment_BDP            as LineSegment_BDP
from LineTable_BDP              import LineTable_BDP              as LineTable_BDP
from Line_BDP                   import Line_BDP                   as Line_BDP
from Moment_BDP                 import Moment_BDP                 as Moment_BDP
from OverlapIntegral_BDP        import OverlapIntegral_BDP        as OverlapIntegral_BDP
from PVCorr_BDP                 import PVCorr_BDP                 as PVCorr_BDP
from PVSlice_BDP                import PVSlice_BDP                as PVSlice_BDP
from PeakPointPlot_BDP          import PeakPointPlot_BDP          as PeakPointPlot_BDP
from SourceList_BDP             import SourceList_BDP             as SourceList_BDP
from SpectralMap_BDP            import SpectralMap_BDP            as SpectralMap_BDP
from SpwCube_BDP                import SpwCube_BDP                as SpwCube_BDP
from Table_BDP                  import Table_BDP                  as Table_BDP
from Table_inherit_BDP          import Table_inherit_BDP          as Table_inherit_BDP
