"""
This file is automatically generated by dtdGenerator.py,
  based on files in admit/bdp and admit/at. Edit this file at your own risk.

This file contains string constants useful for programming
"""

#Generics

GENERIC = "Generic"
ADMIT = "ADMIT"
AT = "AT"
BDP = "BDP"
INT = "INT"
FLOWMANAGER = "flowmanager"
FLOAT = "FLOAT"
DICT = "DICT"
LIST = "LIST"
BOOL = "BOOL"
LONG = "LONG"
STRING = "STRING"
NDARRAY = "NDARRAY"
TUPLE = "TUPLE"
NONE = "NONE"
SET = "SET"
SUMMARY = "SUMMARY"
SUMMARYENTRY = "SUMMARYENTRY"
METADATA = "METADATA"
REQUIRED = "REQ"
OPTIONAL = "OPT"
FOUND = "FOUND"
MISSING = "MISSING"
IMG = "IMG"

# Utility classes

IMAGE = "IMAGE"
LINE = "LINE"
MULTIIMAGE = "MULTIIMAGE"
SOURCE = "SOURCE"
TABLE = "TABLE"
UTIL_LIST = ['Source', 'Image', 'MultiImage', 'Line', 'Table']

# Image types

DATA = "DATA"
THUMB = THUMBNAIL = "THUMBNAIL"
AUX = AUXILIARY = "AUXILIARY"
imagedescriptor_types = [DATA, THUMB, AUX]
FITS = "FITS"
CASA = "CASA"
MIRIAD = "MIRIAD"
GIF = "GIF"
PNG = "PNG"
JPG = "JPG"
PDF = "PDF"
PS = "PS"
SVG = "SVG"

image_types = [FITS, CASA, MIRIAD, GIF, PNG, JPG, PDF, PS, SVG]
# BDP classes

CUBESPECTRUM_BDP = "CubeSpectrum_BDP"
CUBESTATS_BDP = "CubeStats_BDP"
DESCRIPTIONVECTOR_BDP = "DescriptionVector_BDP"
DUAL_INHERIT_BDP = "Dual_inherit_BDP"
FEATURELIST_BDP = "FeatureList_BDP"
FILE_BDP = "File_BDP"
IMAGE_BDP = "Image_BDP"
IMAGE_INHERIT_BDP = "Image_inherit_BDP"
LINECUBE_BDP = "LineCube_BDP"
LINEIMAGE_BDP = "LineImage_BDP"
LINELIST_BDP = "LineList_BDP"
LINESEGMENT_BDP = "LineSegment_BDP"
LINETABLE_BDP = "LineTable_BDP"
LINE_BDP = "Line_BDP"
MOMENT_BDP = "Moment_BDP"
OVERLAPINTEGRAL_BDP = "OverlapIntegral_BDP"
PVCORR_BDP = "PVCorr_BDP"
PVSLICE_BDP = "PVSlice_BDP"
PEAKPOINTPLOT_BDP = "PeakPointPlot_BDP"
SOURCELIST_BDP = "SourceList_BDP"
SPECTRALMAP_BDP = "SpectralMap_BDP"
SPWCUBE_BDP = "SpwCube_BDP"
TABLE_BDP = "Table_BDP"
TABLE_INHERIT_BDP = "Table_inherit_BDP"

# AT classes

BDPINGEST_AT = "BDPIngest_AT"
CONTINUUMMAP_AT = "ContinuumMap_AT"
CONTINUUMSUB_AT = "ContinuumSub_AT"
CUBESPECTRUM_AT = "CubeSpectrum_AT"
CUBESTATS_AT = "CubeStats_AT"
CUBESUM_AT = "CubeSum_AT"
DESCRIPTIONVECTOR_AT = "DescriptionVector_AT"
EXPORT_AT = "Export_AT"
FEATURELIST_AT = "FeatureList_AT"
FILE_AT = "File_AT"
FLOW11_AT = "Flow11_AT"
FLOW1N_AT = "Flow1N_AT"
FLOWMN_AT = "FlowMN_AT"
FLOWN1_AT = "FlowN1_AT"
GENERATESPECTRUM_AT = "GenerateSpectrum_AT"
INGEST_AT = "Ingest_AT"
LINECUBE_AT = "LineCube_AT"
LINEID_AT = "LineID_AT"
LINESEGMENT_AT = "LineSegment_AT"
MOMENT_AT = "Moment_AT"
OVERLAPINTEGRAL_AT = "OverlapIntegral_AT"
PVCORR_AT = "PVCorr_AT"
PVSLICE_AT = "PVSlice_AT"
PRINCIPALCOMPONENT_AT = "PrincipalComponent_AT"
REGRID_AT = "Regrid_AT"
SFIND2D_AT = "SFind2D_AT"
SMOOTH_AT = "Smooth_AT"
SPECTRALMAP_AT = "SpectralMap_AT"
SPWCUBE_AT = "SpwCube_AT"
TEMPLATE_AT = "Template_AT"
TEST_AT = "Test_AT"


class color:
    PURPLE = ''
    CYAN = ''
    DARKCYAN = ''
    BLUE = ''
    GREEN = ''
    YELLOW = ''
    RED = ''
    END = ''


class format:
    BOLD = ''
    UNDERLINE = ''
    END = ''
